mate-terminal -e "/home/fabio/unicamp/mc920/venv/bin/python /home/fabio/unicamp/mc920/T3/alinhar.py /home/fabio/unicamp/mc920/T3/neg_4.png 1 /home/fabio/unicamp/mc920/T3/neg_4_aligned_hzpj.png"
mate-terminal -e "/home/fabio/unicamp/mc920/venv/bin/python /home/fabio/unicamp/mc920/T3/alinhar.py /home/fabio/unicamp/mc920/T3/neg_28.png 1 /home/fabio/unicamp/mc920/T3/neg_28_aligned_hzpj.png"
mate-terminal -e "/home/fabio/unicamp/mc920/venv/bin/python /home/fabio/unicamp/mc920/T3/alinhar.py /home/fabio/unicamp/mc920/T3/pos_24.png 1 /home/fabio/unicamp/mc920/T3/pos_24_aligned_hzpj.png"
mate-terminal -e "/home/fabio/unicamp/mc920/venv/bin/python /home/fabio/unicamp/mc920/T3/alinhar.py /home/fabio/unicamp/mc920/T3/pos_41.png 1 /home/fabio/unicamp/mc920/T3/pos_41_aligned_hzpj.png"
mate-terminal -e "/home/fabio/unicamp/mc920/venv/bin/python /home/fabio/unicamp/mc920/T3/alinhar.py /home/fabio/unicamp/mc920/T3/sample1.png 1 /home/fabio/unicamp/mc920/T3/sample1_aligned_hzpj.pn"
mate-terminal -e "/home/fabio/unicamp/mc920/venv/bin/python /home/fabio/unicamp/mc920/T3/alinhar.py /home/fabio/unicamp/mc920/T3/sample2.png 1 /home/fabio/unicamp/mc920/T3/sample2_aligned_hzpj.png"

mate-terminal -e "/home/fabio/unicamp/mc920/venv/bin/python /home/fabio/unicamp/mc920/T3/alinhar.py /home/fabio/unicamp/mc920/T3/neg_4.png 2 /home/fabio/unicamp/mc920/T3/neg_4_aligned_hough.png"
mate-terminal -e "/home/fabio/unicamp/mc920/venv/bin/python /home/fabio/unicamp/mc920/T3/alinhar.py /home/fabio/unicamp/mc920/T3/neg_28.png 2 /home/fabio/unicamp/mc920/T3/neg_28_aligned_hough.png"
mate-terminal -e "/home/fabio/unicamp/mc920/venv/bin/python /home/fabio/unicamp/mc920/T3/alinhar.py /home/fabio/unicamp/mc920/T3/pos_24.png 2 /home/fabio/unicamp/mc920/T3/pos_24_aligned_hough.png"
mate-terminal -e "/home/fabio/unicamp/mc920/venv/bin/python /home/fabio/unicamp/mc920/T3/alinhar.py /home/fabio/unicamp/mc920/T3/pos_41.png 2 /home/fabio/unicamp/mc920/T3/pos_41_aligned_hough.png"
mate-terminal -e "/home/fabio/unicamp/mc920/venv/bin/python /home/fabio/unicamp/mc920/T3/alinhar.py /home/fabio/unicamp/mc920/T3/sample1.png 2 /home/fabio/unicamp/mc920/T3/sample1_aligned_hough.png"
mate-terminal -e "/home/fabio/unicamp/mc920/venv/bin/python /home/fabio/unicamp/mc920/T3/alinhar.py /home/fabio/unicamp/mc920/T3/sample2.png 2 /home/fabio/unicamp/mc920/T3/sample2_aligned_hough.png"
